    - name: Install AD-Domain-Services feature
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        include_sub_features: yes
        state: present

    - name: setup domain controller
      win_domain: 
        dns_domain_name: "{{ ad_domain_name }}"
        safe_mode_password: "{{ ad_safe_mode_password }}"
      register: result

    - name: Reboots the instance
      win_reboot:
      when: result.reboot_required

    - name: List Domain Controllers in domain
      win_shell: "nltest /dclist:{{ ad_domain_name }}"
      register: domainlist

    - debug: 
       var: domainlist
